### ISSUE TITLE
faulty Hash option

### ISSUE THREAD

**Issue by tissatussa** [Heiaha/Weiawaga#3]
i just compiled the newest source code into a valid Linux binary and it works in CuteChess.

however, in the CuteChess settings i see that the Hash value can not be set, it can only be reset to its default value (512 Mb).
it seems you did not properly define the Hash option :

`UciOptionMap({'Hash': Option(name='Hash', type='spin', default=512, min=None, max=None, var=[])})`

'min' and 'max' are None, which gives this error : the up / down counter form element does not work .. please correct this.

**Comment by Heiaha** [comment]
sure.

**Comment by tissatussa** [comment]
today i'm testing Weiawaga and it seems it has a rating around 2550 .. what do you think ?  it's not mentioned in the CCRL lists.

i find it plays good moves : it has some own basic setup in the opening (playing 1.Nf3, 1.e4 and 1.d4) with an early e2-e3 and a sound strategy with lots of tactics .. i like its style!
One flaw was in this endgame against Yace v0.99.50 (rating 2486) :
5bk1/6p1/5p1p/B2R4/8/r5P1/5PP1/6K1 w - - 0 36

![Weiawaga_lost_against_Yace](https://user-images.githubusercontent.com/1109281/148602012-e0802616-eaec-4205-b644-c04e76ac7e39.png)

White to move.
It seems this is a draw but Weiawaga lost this game .. here's the PGN : [Weiawaga_lost_against_Yace.zip](https://github.com/Heiaha/Weiawaga/files/7831154/Weiawaga_lost_against_Yace.zip)

so Weiawaga needs to improve in the endgame ..

apart from that : well done !
Btw. it has no version number ?

**Comment by Heiaha** [comment]
I haven't started versioning yet, but plan to in the future (most likely after implementing multithreading). Probably I'll put it on CCRL at that point. This repository is still a bit of a work in progress after porting from a previous Java engine (https://github.com/Heiaha/WeiawagaJ), which I never put on CCRL because it was just using a hash map for the transposition table at that time and wasn't limiting its size, which wouldn't have been acceptable for CCRL.

Thanks for testing it out!

**Comment by tissatussa** [comment]
OK.
What rating does it have ?  What's your guess ?
And do you admit it lacks some endgame skills ? It's a pitty that game was lost .. it seems Weiawaga was pushing too hard ..
